# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/jfishe/vimwiki-cli.git
    rev: ce89fe5dfd2e1135b37c57836b39cee4424ab3ce
    hooks:
      - id: vimwiki-cli
        stages:
          - pre-commit
          - pre-push
  - repo: local
    hooks:
      - id: ghp-import
        name: Update Github Pages
        entry: .pre_commit_hooks/gh-pages.sh
        language: script
        require_serial: true
        stages:
          - pre-push
